# Site settings
baseurl = "https://omnibus.live/"
languageCode = "en-us"
title = "Omnibus Live"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
# googleAnalytics = ""
# Disable comments by leaving disqusShortname empty

[params]
	name = "Omnibus Live"
	description = "This website is about Forex's latest information"
	bio = "Blogger & Trader"
	# Enter optionally your twitter account
	twitter = "FxPlayground"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I'm a blogger and trader."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://twitter.com/FxPlayground"
    github   = "https://www.github.com/playgroundfx"
